### ISSUE TITLE
node demo.js 的时候报错  timers.js:319

### ISSUE THREAD

**Issue by vmvz** [ssdb/nodessdb#10]
```
root@debian:~/nodessdb# node demo.js 
timers.js:319
    throw new TypeError('"msecs" argument must be a number');
    ^

TypeError: "msecs" argument must be a number
    at Object.exports.enroll (timers.js:319:11)
    at Socket.setTimeout (net.js:340:12)
    at Socket.<anonymous> (/root/nodessdb/SSDB.js:39:8)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:188:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:10)

```

**Comment by ideawu** [comment]
应该是你的node环境有问题。
